/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.panels;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import ni.edu.uni.list.ActivosList;
import static ni.edu.uni.panels.tblLRPanel.depreciacion;
import ni.edu.uni.pojo.Activo;

/**
 *
 * @author Sistemas-15
 */
public class TblSDAPanel extends javax.swing.JPanel { 
    static final float suma_anios = (5 * (5 + 1))/2;
    private final String columns[] = {"Tipo", "1", "2", "3", "4", "5"};
    addPanel add;
    DefaultTableModel model;
    ActivosList list;
    /**
     * Creates new form tblLRPanel
     */
    public TblSDAPanel() {
        initComponents();
        initTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public static float depreciacion(float v, float r) {
        return ((v - r) * 5.0f) / suma_anios;
    }
    
    public void initTable() {
        add = new addPanel();
        list = new ActivosList();
        String[][] data = new String[list.getActivos().size()][5];
        for(int i = 0; i < list.getActivos().size(); i++) {
            data[i][0] = list.getActivos().get(i).getTipo();
            data[i][1] = String.valueOf(depreciacion(list.getActivos().get(i).getValor_bien(), list.getActivos().get(i).getValor_residual()));
            data[i][2] = String.valueOf(depreciacion(list.getActivos().get(i).getValor_bien(), list.getActivos().get(i).getValor_residual()));
            data[i][3] = String.valueOf(depreciacion(list.getActivos().get(i).getValor_bien(), list.getActivos().get(i).getValor_residual()));
            data[i][4] = String.valueOf(depreciacion(list.getActivos().get(i).getValor_bien(), list.getActivos().get(i).getValor_residual()));
            data[i][5] = String.valueOf(depreciacion(list.getActivos().get(i).getValor_bien(), list.getActivos().get(i).getValor_residual()));
        }
        model = new DefaultTableModel(data, columns);
        jTable1.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
